"""updated field updated_at

Revision ID: 389f20877700
Revises: eda3ff0f2694
Create Date: 2021-03-05 02:45:45.509802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '389f20877700'
down_revision = 'eda3ff0f2694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=30), nullable=True))
    op.drop_column('user', 'updted_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updted_at', mysql.DATETIME(), nullable=True))
    op.drop_column('user', 'updated_at')
    # ### end Alembic commands ###
